Repository toyland/toyland-project, pull requests merged in 2025-02, with the labels that each got.

#9 Feature/#4 회원생성
  build.gradle
  docker-compose.yml
  src/main/java/com/toyland/user/application/UserService.java
  src/main/java/com/toyland/user/config/PasswordConfig.java
  src/main/java/com/toyland/user/model/User.java
  src/main/java/com/toyland/user/model/UserRoleEnum.java
  src/main/java/com/toyland/user/model/repository/UserRepository.java
  src/main/java/com/toyland/user/presentation/UserController.java
  src/main/java/com/toyland/user/presentation/dto/SignupRequestDto.java
  src/main/java/com/toyland/user/presentation/dto/SignupResponseDto.java
  src/main/resources/application.yml
Labels: ✨ feat

#13 Remove/#12 파일 삭제
  .github/workflows/deploy.yml
Labels: 🔥 remove

#16 Refactor/#11 BaseEntity 삭제 필드 기능 수정 및 gitignore 수정
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/toyland/ToylandApplication.java
  src/main/java/com/toyland/global/config/auditing/AuditorAwareImpl.java
  src/main/java/com/toyland/global/config/auditing/BaseEntity.java
  src/main/java/com/toyland/global/config/auditing/BaseRepository.java
  src/main/java/com/toyland/global/config/auditing/JpaAuditingConfig.java
  src/main/resources/application.yml
Labels: ♻️ refactor, ✨ feat

#17 Feature/#6 [category] 생성
  .gitignore
  build.gradle
  src/main/java/com/toyland/category/application/facade/CategoryFacade.java
  src/main/java/com/toyland/category/application/facade/CategoryFacadeImpl.java
  src/main/java/com/toyland/category/application/usecase/CategoryService.java
  src/main/java/com/toyland/category/application/usecase/CategoryServiceImpl.java
  src/main/java/com/toyland/category/infrastructure/JpaCategoryRepository.java
  src/main/java/com/toyland/category/model/entity/Category.java
  src/main/java/com/toyland/category/model/repository/CategoryRepository.java
  src/main/java/com/toyland/category/presentation/CategoryController.java
  src/main/java/com/toyland/category/presentation/dto/CreateCategoryRequestDto.java
  src/main/resources/application-test.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/http/category.http
  src/test/java/com/toyland/category/application/usecase/CategoryServiceTest.java
  src/test/java/com/toyland/common/IntegrationTestSupport.java
Labels: ✅ test, ✨ feat

#23 [#15]feat: 주문 생성
  src/main/java/com/toyland/category/model/entity/Category.java
  src/main/java/com/toyland/order/model/Order.java
  src/main/java/com/toyland/order/model/OrderStatus.java
  src/main/java/com/toyland/order/model/OrderType.java
  src/main/java/com/toyland/order/model/PaymentType.java
  src/main/java/com/toyland/user/model/User.java
Labels: ✨ feat

#24 feature/#18 [Address] 생성
  build.gradle
  src/main/java/com/toyland/address/application/facade/AddressFacade.java
  src/main/java/com/toyland/address/application/facade/AddressFacadeImpl.java
  src/main/java/com/toyland/address/application/usecase/AddressService.java
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/infrastructure/JpaAddressRepository.java
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/address/model/repository/AddressRepository.java
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/address/presentation/dto/AddressResponseDto.java
  src/main/java/com/toyland/address/presentation/dto/CreateAddressRequestDto.java
  src/main/java/com/toyland/global/common/auditing/AuditorAwareImpl.java
  src/main/java/com/toyland/global/common/auditing/BaseEntity.java
  src/main/java/com/toyland/global/common/auditing/BaseRepository.java
  src/main/java/com/toyland/global/config/JpaAuditingConfig.java
  src/main/java/com/toyland/user/model/User.java
  src/test/http/address.http
  src/test/java/com/toyland/address/application/usecase/AddressServiceImplTest.java
Labels: ✅ test, ✨ feat

#26 Feature/#19 [store] 생성
  src/main/java/com/toyland/store/application/facade/StoreFacade.java
  src/main/java/com/toyland/store/application/facade/StoreFacadeImpl.java
  src/main/java/com/toyland/store/application/usecase/StoreService.java
  src/main/java/com/toyland/store/application/usecase/StoreServiceImpl.java
  src/main/java/com/toyland/store/infrastructure/JpaStoreRepository.java
  src/main/java/com/toyland/store/model/entity/Store.java
  src/main/java/com/toyland/store/model/repository/StoreRepository.java
  src/main/java/com/toyland/store/presentation/StoreController.java
  src/main/java/com/toyland/store/presentation/dto/CreateStoreRequestDto.java
  src/test/http/store.http
  src/test/java/com/toyland/store/application/usecase/StoreServiceTest.java
Labels: ✅ test, ✨ feat

#27 Feature/#25 [exception] Global 예외처리 로직 구성
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/address/presentation/dto/AddressResponseDto.java
  src/main/java/com/toyland/global/exception/CustomException.java
  src/main/java/com/toyland/global/exception/ErrorResponse.java
  src/main/java/com/toyland/global/exception/GlobalErrorHandler.java
  src/main/java/com/toyland/global/exception/type/ApiErrorCode.java
  src/main/java/com/toyland/global/exception/type/BusinessErrorCode.java
  src/main/java/com/toyland/global/exception/type/ErrorCode.java
Labels: ♻️ refactor, ✨ feat

#31 [#30] 주문 엔티티 필드 이름 수정
  src/main/java/com/toyland/order/model/Order.java
Labels: ♻️ refactor

#33 Feature/#29 지역 생성 및 테스트
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/address/presentation/dto/CreateAddressRequestDto.java
  src/main/java/com/toyland/global/exception/type/BusinessErrorCode.java
  src/main/java/com/toyland/region/application/facade/RegionFacade.java
  src/main/java/com/toyland/region/application/facade/RegionFacadeImpl.java
  src/main/java/com/toyland/region/application/usecase/RegionService.java
  src/main/java/com/toyland/region/application/usecase/RegionServiceImpl.java
  src/main/java/com/toyland/region/infrastructure/JpaRegionRepository.java
  src/main/java/com/toyland/region/model/entity/Region.java
  src/main/java/com/toyland/region/model/repository/RegionRepository.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/java/com/toyland/region/presentation/dto/CreateRegionRequestDto.java
  src/main/java/com/toyland/region/presentation/dto/RegionResponseDto.java
  src/test/http/address.http
  src/test/http/region.http
  src/test/java/com/toyland/address/application/usecase/AddressServiceImplTest.java
Labels: ♻️ refactor, ✅ test, ✨ feat

#32 feature/#21 [Security] jwt 토큰 방식 구현
  src/main/java/com/toyland/ToylandApplication.java
  src/main/java/com/toyland/global/config/security/UserDetailsImpl.java
  src/main/java/com/toyland/global/config/security/UserDetailsServiceImpl.java
  src/main/java/com/toyland/global/config/security/WebSecurityConfig.java
  src/main/java/com/toyland/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/toyland/global/config/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/toyland/global/config/security/jwt/JwtUtil.java
  src/main/java/com/toyland/user/application/UserService.java
  src/main/java/com/toyland/user/presentation/UserController.java
  src/test/http/user.http
Labels: ✨ feat

#28 [#14] feat: ai 문답 내용 저장
  build.gradle
  src/main/java/com/toyland/ToylandApplication.java
  src/main/java/com/toyland/ai/application/QnaService.java
  src/main/java/com/toyland/ai/config/QnaConfig.java
  src/main/java/com/toyland/ai/model/AiComp.java
  src/main/java/com/toyland/ai/model/Qna.java
  src/main/java/com/toyland/ai/model/repository/QnaRepository.java
  src/main/java/com/toyland/ai/presentation/OpenApiFeignClient.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/ai/presentation/dto/AiRequestDto.java
  src/main/java/com/toyland/ai/presentation/dto/AiResponseDto.java
  src/main/java/com/toyland/ai/presentation/dto/Message.java
  src/main/java/com/toyland/ai/presentation/dto/QnaRequestDto.java
  src/main/java/com/toyland/global/config/ai/OpenApiFeignConfig.java
  src/main/resources/application.yml
Labels: ♻️ refactor, ✨ feat

#41 Refactor/#36 BasceEntity 리팩토링 및 테스트
  src/main/java/com/toyland/global/common/auditing/AuditorAwareImpl.java
  src/main/java/com/toyland/global/common/auditing/BaseEntity.java
  src/main/java/com/toyland/global/common/auditing/BaseRepository.java
  src/main/java/com/toyland/region/model/entity/Region.java
  src/main/java/com/toyland/user/config/PasswordConfig.java
Labels: ♻️ refactor, 💡 comments, ✨ feat

#38 Feature/#34 [OrderProduct] 주문상품 생성, 주문과 외래키(연관관계) 설정
  src/main/java/com/toyland/order/model/Order.java
  src/main/java/com/toyland/orderproduct/model/OrderProduct.java
  src/main/java/com/toyland/user/model/User.java
Labels: ✨ feat

#43 feature/#35 지역 RUD 구현 및 테스트
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/global/common/auditing/BaseEntity.java
  src/main/java/com/toyland/global/exception/type/BusinessErrorCode.java
  src/main/java/com/toyland/region/application/facade/RegionFacade.java
  src/main/java/com/toyland/region/application/facade/RegionFacadeImpl.java
  src/main/java/com/toyland/region/application/usecase/RegionService.java
  src/main/java/com/toyland/region/application/usecase/RegionServiceImpl.java
  src/main/java/com/toyland/region/model/entity/Region.java
  src/main/java/com/toyland/region/model/repository/RegionRepository.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/java/com/toyland/region/presentation/dto/CreateRegionRequestDto.java
  src/test/http/region.http
  src/test/java/com/toyland/region/application/usecase/RegionServiceImplTest.java
Labels: ✅ test, ✨ feat

#48 refactor/#46 Exception 처리 리팩토링
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/category/application/usecase/CategoryServiceImpl.java
  src/main/java/com/toyland/global/exception/GlobalErrorHandler.java
  src/main/java/com/toyland/global/exception/type/BusinessErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/AddressErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/CategoryErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/RegionErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/UserErrorCode.java
  src/main/java/com/toyland/region/application/usecase/RegionServiceImpl.java
  src/main/java/com/toyland/user/application/UserService.java
  src/test/http/address.http
Labels: ♻️ refactor, ✨ feat

#53 Feature/#47 [store] 음식점 지역, 유저 fk 추가
  src/main/java/com/toyland/store/application/usecase/StoreServiceImpl.java
  src/main/java/com/toyland/store/model/entity/Store.java
  src/main/java/com/toyland/store/presentation/dto/CreateStoreRequestDto.java
  src/test/http/store.http
  src/test/java/com/toyland/store/application/usecase/StoreServiceTest.java
Labels: ♻️ refactor, ✨ feat

#51 Feature/#40 [AI] AI문답 단일 및 전체 조회
  src/main/java/com/toyland/ai/application/QnaService.java
  src/main/java/com/toyland/ai/infrastructure/JpaAIRepository.java
  src/main/java/com/toyland/ai/model/Qna.java
  src/main/java/com/toyland/ai/model/repository/QnaRepository.java
  src/main/java/com/toyland/ai/model/repository/QnaRepositoryCustom.java
  src/main/java/com/toyland/ai/model/repository/QnaRepositoryCustomImpl.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/ai/presentation/dto/PagedResponse.java
  src/main/java/com/toyland/ai/presentation/dto/QnaRequestDto.java
  src/main/java/com/toyland/ai/presentation/dto/QnaResponseDto.java
  src/test/http/aiqna.http
Labels: ✨ feat

#52 Feature/#44 Address RUD 기능 생성 및 테스트
  src/main/java/com/toyland/address/application/facade/AddressFacade.java
  src/main/java/com/toyland/address/application/facade/AddressFacadeImpl.java
  src/main/java/com/toyland/address/application/usecase/AddressService.java
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/address/model/repository/AddressRepository.java
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/address/presentation/dto/CreateAddressRequestDto.java
  src/main/java/com/toyland/region/model/repository/RegionRepository.java
  src/test/http/address.http
  src/test/http/region.http
  src/test/java/com/toyland/address/application/usecase/AddressServiceImplTest.java
  src/test/java/com/toyland/region/application/usecase/RegionServiceImplTest.java
Labels: ♻️ refactor, ✅ test, ✨ feat

#63 [AI] Qna Update 및 Delete 생성
  src/main/java/com/toyland/ai/application/QnaService.java
  src/main/java/com/toyland/ai/model/Qna.java
  src/main/java/com/toyland/ai/model/repository/QnaRepository.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/ai/presentation/dto/AiqnaResponse.java
  src/main/java/com/toyland/ai/presentation/dto/QnaRequestDto.java
  src/main/java/com/toyland/ai/presentation/dto/QnaResponseDto.java
  src/test/http/aiqna.http
Labels: ♻️ refactor, ✨ feat

#69 Feature/#49 [AI] QueryDSL 오류 수정
  src/main/java/com/toyland/ai/application/QnaService.java
  src/main/java/com/toyland/ai/infrastructure/JpaQnaRepository.java
  src/main/java/com/toyland/ai/infrastructure/impl/QnaRepositoryCustomImpl.java
  src/main/java/com/toyland/ai/model/Qna.java
  src/main/java/com/toyland/ai/model/repository/QnaRepository.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/test/http/aiqna.http
Labels: 🐛 bug

#62 [User] 조회,테스트 코드 추가
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/global/common/auditing/AuditorAwareImpl.java
  src/main/java/com/toyland/global/config/security/UserDetailsImpl.java
  src/main/java/com/toyland/global/config/security/UserDetailsServiceImpl.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/java/com/toyland/user/application/UserService.java
  src/main/java/com/toyland/user/model/User.java
  src/main/java/com/toyland/user/presentation/UserController.java
  src/main/java/com/toyland/user/presentation/dto/UpdateUserRequestDto.java
  src/main/java/com/toyland/user/presentation/dto/UpdateUserResponseDto.java
  src/main/java/com/toyland/user/presentation/dto/UserDto.java
  src/main/java/com/toyland/user/presentation/dto/UserResponseDto.java
  src/test/http/user.http
  src/test/java/com/toyland/user/apllication/usecase/UserServiceTest.java
Labels: ♻️ refactor, ✅ test, ✨ feat

#67 Feature/#56 지역 도메인 동적 검색 기능 생성
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/region/application/facade/RegionFacade.java
  src/main/java/com/toyland/region/application/facade/RegionFacadeImpl.java
  src/main/java/com/toyland/region/application/usecase/RegionService.java
  src/main/java/com/toyland/region/application/usecase/RegionServiceImpl.java
  src/main/java/com/toyland/region/infrastructure/Impl/JpaRegionRepositoryCustomImpl.java
  src/main/java/com/toyland/region/infrastructure/JpaRegionRepository.java
  src/main/java/com/toyland/region/infrastructure/JpaRegionRepositoryCustom.java
  src/main/java/com/toyland/region/model/entity/Region.java
  src/main/java/com/toyland/region/model/repository/RegionRepository.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/java/com/toyland/region/presentation/dto/CreateRegionRequestDto.java
  src/main/java/com/toyland/region/presentation/dto/repuest/CreateRegionRequestDto.java
  src/main/java/com/toyland/region/presentation/dto/repuest/RegionSearchRequestDto.java
  src/main/java/com/toyland/region/presentation/dto/response/RegionResponseDto.java
  src/main/java/com/toyland/region/presentation/dto/response/RegionSearchResponseDto.java
  src/main/java/com/toyland/store/model/repository/StoreRepository.java
  src/test/http/region.http
  src/test/java/com/toyland/common/IntegrationTestSupport.java
  src/test/java/com/toyland/region/application/usecase/RegionServiceImplTest.java
Labels: ✅ test, ✨ feat

#65 refactor/#50 음식점 카테고리 set api 구현
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/category/model/repository/CategoryRepository.java
  src/main/java/com/toyland/global/common/auditing/BaseEntity.java
  src/main/java/com/toyland/global/config/security/annotation/CurrentLoginUserId.java
  src/main/java/com/toyland/global/exception/type/domain/CategoryErrorCode.java
  src/main/java/com/toyland/store/application/facade/StoreFacade.java
  src/main/java/com/toyland/store/application/facade/StoreFacadeImpl.java
  src/main/java/com/toyland/store/application/usecase/StoreService.java
  src/main/java/com/toyland/store/application/usecase/StoreServiceImpl.java
  src/main/java/com/toyland/store/application/usecase/dto/CreateStoreCategoryListServiceRequestDto.java
  src/main/java/com/toyland/store/presentation/StoreController.java
  src/main/java/com/toyland/store/presentation/dto/CreateStoreCategoryListRequestDto.java
  src/main/java/com/toyland/storecategory/infrastructure/JpaStoreCategoryRepository.java
  src/main/java/com/toyland/storecategory/model/entity/StoreCategory.java
  src/main/java/com/toyland/storecategory/model/repository/StoreCategoryRepository.java
  src/test/http/category.http
  src/test/http/store.http
  src/test/java/com/toyland/store/application/usecase/StoreServiceTest.java
Labels: ✅ test, ✨ feat

#75 Feature/#66 [product] 단건 조회
  src/main/java/com/toyland/product/application/usecase/ProductService.java
  src/main/java/com/toyland/product/application/usecase/ProductServiceImpl.java
  src/main/java/com/toyland/product/model/repository/ProductRepository.java
  src/main/java/com/toyland/product/presentaion/ProductController/ProductController.java
  src/main/java/com/toyland/product/presentaion/dto/ReadProductResponseDto.java
  src/test/http/product.http
  src/test/java/com/toyland/product/application/usecase/ProductServiceTest.java
Labels: ✅ test, ✨ feat

#74 Feature/#70 Address 동적 검색 생성 및 테스트
  src/main/java/com/toyland/address/application/facade/AddressFacade.java
  src/main/java/com/toyland/address/application/facade/AddressFacadeImpl.java
  src/main/java/com/toyland/address/application/usecase/AddressService.java
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/infrastructure/JpaAddressRepository.java
  src/main/java/com/toyland/address/infrastructure/JpaAddressRepositoryCustom.java
  src/main/java/com/toyland/address/infrastructure/impl/JpaAddressRepositoryCustomImpl.java
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/address/model/repository/AddressRepository.java
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/address/presentation/dto/request/AddressSearchRequestDto.java
  src/main/java/com/toyland/address/presentation/dto/request/CreateAddressRequestDto.java
  src/main/java/com/toyland/address/presentation/dto/response/AddressResponseDto.java
  src/main/java/com/toyland/address/presentation/dto/response/AddressSearchResponseDto.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/region/model/entity/Region.java
  src/test/http/address.http
  src/test/http/region.http
  src/test/java/com/toyland/address/application/usecase/AddressServiceImplTest.java
Labels: ✅ test, ✨ feat

#73 [Review] Review 생성, 조회
  src/main/java/com/toyland/ai/infrastructure/JpaQnaRepository.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/ai/presentation/dto/QnaResponseDto.java
  src/main/java/com/toyland/order/model/repository/OrderRepository.java
  src/main/java/com/toyland/review/application/facade/ReviewFacade.java
  src/main/java/com/toyland/review/application/facade/ReviewFacadeImpl.java
  src/main/java/com/toyland/review/application/usecase/ReviewService.java
  src/main/java/com/toyland/review/application/usecase/ReviewServiceImpl.java
  src/main/java/com/toyland/review/infrastructure/JpaReviewRepository.java
  src/main/java/com/toyland/review/infrastructure/ReviewRepositoryCustom.java
  src/main/java/com/toyland/review/infrastructure/impl/ReviewRepositoryCustomImpl.java
  src/main/java/com/toyland/review/model/Review.java
  src/main/java/com/toyland/review/model/repository/ReviewRepository.java
  src/main/java/com/toyland/review/presentation/ReviewController.java
  src/main/java/com/toyland/review/presentation/dto/ReviewRequestDto.java
  src/main/java/com/toyland/review/presentation/dto/ReviewResponseDto.java
  src/test/http/aiqna.http
  src/test/http/product.http
  src/test/http/review.http
Labels: ✨ feat

#79 [#78] bug: 에러 수정
  src/main/java/com/toyland/address/infrastructure/impl/JpaAddressRepositoryCustomImpl.java
  src/main/java/com/toyland/ai/infrastructure/impl/QnaRepositoryCustomImpl.java
  src/main/java/com/toyland/product/model/repository/ProductRepository.java
  src/main/java/com/toyland/region/infrastructure/Impl/JpaRegionRepositoryCustomImpl.java
  src/main/java/com/toyland/review/infrastructure/impl/ReviewRepositoryCustomImpl.java
Labels: 🐛 bug

#81 Feature/#76 product update api 구현
  src/main/java/com/toyland/product/application/usecase/ProductService.java
  src/main/java/com/toyland/product/application/usecase/ProductServiceImpl.java
  src/main/java/com/toyland/product/application/usecase/dto/UpdateProductServiceRequestDto.java
  src/main/java/com/toyland/product/model/entity/Product.java
  src/main/java/com/toyland/product/presentaion/ProductController/ProductController.java
  src/main/java/com/toyland/product/presentaion/dto/ProductResponseDto.java
  src/main/java/com/toyland/product/presentaion/dto/UpdateProductRequestDto.java
  src/test/http/product.http
  src/test/java/com/toyland/product/application/usecase/ProductServiceTest.java
Labels: ✅ test, ✨ feat

#83 Feature/#68 [Order] 주문 삭제 api 작성
  src/main/java/com/toyland/global/exception/type/domain/OrderErrorCode.java
  src/main/java/com/toyland/order/application/OrderService.java
  src/main/java/com/toyland/order/model/Order.java
  src/main/java/com/toyland/order/model/repository/OrderRepository.java
  src/main/java/com/toyland/order/presentation/OrderController.java
  src/main/java/com/toyland/orderproduct/model/OrderProduct.java
  src/main/java/com/toyland/user/model/repository/UserRepository.java
  src/test/http/order.http
  src/test/java/com/toyland/order/application/OrderServiceTest.java
Labels: ✨ feat

#86 Feature/#82 product delete 구현
  src/main/java/com/toyland/product/application/usecase/ProductService.java
  src/main/java/com/toyland/product/application/usecase/ProductServiceImpl.java
  src/main/java/com/toyland/product/application/usecase/dto/DeleteProductServiceRequestDto.java
  src/main/java/com/toyland/product/presentaion/ProductController/ProductController.java
  src/test/http/product.http
  src/test/java/com/toyland/product/application/usecase/ProductServiceTest.java
Labels: ✅ test, ✨ feat

#90 Feature/#71 회원검색기능 추가
  src/main/java/com/toyland/user/application/UserService.java
  src/main/java/com/toyland/user/infrastructure/Impl/JpaUserRepositoryCustomImpl.java
  src/main/java/com/toyland/user/infrastructure/JpaUserRepositoryCustom.java
  src/main/java/com/toyland/user/infrastructure/UserSortEnum.java
  src/main/java/com/toyland/user/model/UserRoleEnum.java
  src/main/java/com/toyland/user/model/repository/UserRepository.java
  src/main/java/com/toyland/user/presentation/UserController.java
  src/main/java/com/toyland/user/presentation/dto/UserSearchRequestDto.java
  src/main/java/com/toyland/user/presentation/dto/UserSearchResponseDto.java
  src/test/http/user.http
  src/test/java/com/toyland/user/apllication/usecase/UserServiceTest.java
Labels: ✨ feat

#88 [#77] refactor: 지역 도메인 리팩토링 및 테스트, 에러처리 확장
  src/main/java/com/toyland/address/infrastructure/impl/JpaAddressRepositoryCustomImpl.java
  src/main/java/com/toyland/global/common/auditing/BaseEntity.java
  src/main/java/com/toyland/global/config/security/WebSecurityConfig.java
  src/main/java/com/toyland/global/exception/GlobalErrorHandler.java
  src/main/java/com/toyland/region/application/usecase/RegionServiceImpl.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/java/com/toyland/region/presentation/dto/repuest/CreateRegionRequestDto.java
  src/main/java/com/toyland/region/presentation/dto/response/RegionResponseDto.java
  src/main/java/com/toyland/region/presentation/dto/response/RegionSearchResponseDto.java
  src/test/http/region.http
  src/test/http/user.http
Labels: ♻️ refactor, ✅ test, ✨ feat

#96 Feature/#89 [Order] 주문 단 건 조회 api 추가
  src/main/java/com/toyland/global/config/security/WebSecurityConfig.java
  src/main/java/com/toyland/global/exception/type/domain/OrderErrorCode.java
  src/main/java/com/toyland/order/application/OrderService.java
  src/main/java/com/toyland/order/presentation/OrderController.java
  src/main/java/com/toyland/order/presentation/dto/response/OrderProductResponseDto.java
  src/main/java/com/toyland/order/presentation/dto/response/OrderResponseDto.java
  src/test/http/order.http
Labels: ✨ feat

#100 Feature/#97 payment 도메인 생성 및 생성 로직 작성
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/address/presentation/dto/response/AddressResponseDto.java
  src/main/java/com/toyland/address/presentation/dto/response/AddressSearchResponseDto.java
  src/main/java/com/toyland/global/config/security/WebSecurityConfig.java
  src/main/java/com/toyland/order/model/Order.java
  src/main/java/com/toyland/payment/application/facade/PaymentFacade.java
  src/main/java/com/toyland/payment/application/facade/PaymentFacadeImpl.java
  src/main/java/com/toyland/payment/application/usecase/PaymentService.java
  src/main/java/com/toyland/payment/application/usecase/PaymentServiceImpl.java
  src/main/java/com/toyland/payment/infrastructure/JpaPaymentRepository.java
  src/main/java/com/toyland/payment/model/entity/Payment.java
  src/main/java/com/toyland/payment/model/repository/PaymentRepository.java
  src/main/java/com/toyland/payment/presentation/PaymentController.java
  src/main/java/com/toyland/payment/presentation/dto/request/PaymentRequestDto.java
  src/main/java/com/toyland/payment/presentation/dto/response/PaymentResponseDto.java
  src/main/java/com/toyland/product/application/facade/ProductFacade.java
  src/main/java/com/toyland/product/application/facade/ProductFacadeImpl.java
  src/main/java/com/toyland/product/application/usecase/ProductService.java
  src/main/java/com/toyland/product/application/usecase/ProductServiceImpl.java
  src/main/java/com/toyland/product/application/usecase/dto/CreateProductServiceRequestDto.java
  src/main/java/com/toyland/product/application/usecase/dto/UpdateProductServiceRequestDto.java
  src/main/java/com/toyland/product/presentaion/ProductController/ProductController.java
  src/main/java/com/toyland/product/presentaion/dto/ProductResponseDto.java
  src/main/java/com/toyland/product/presentation/ProductController/ProductController.java
  src/main/java/com/toyland/product/presentation/dto/CreateProductRequestDto.java
  src/main/java/com/toyland/product/presentation/dto/ProductResponseDto.java
  src/main/java/com/toyland/product/presentation/dto/UpdateProductRequestDto.java
  src/main/java/com/toyland/region/infrastructure/Impl/JpaRegionRepositoryCustomImpl.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/test/http/region.http
  src/test/java/com/toyland/payment/application/usecase/PaymentServiceImplTest.java
  src/test/java/com/toyland/product/application/facade/ProductFacadeTest.java
  src/test/java/com/toyland/product/application/usecase/ProductServiceTest.java
Labels: ✅ test, ✨ feat

#95 refactor/#91 Address 도메인 전체적 리팩토링
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/address/presentation/dto/response/AddressResponseDto.java
  src/main/java/com/toyland/address/presentation/dto/response/AddressSearchResponseDto.java
  src/main/java/com/toyland/region/infrastructure/Impl/JpaRegionRepositoryCustomImpl.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/test/http/region.http
Labels: ♻️ refactor

#85 Feature/#80 Review 수정 및 삭제
  src/main/java/com/toyland/ai/application/QnaService.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/global/exception/type/domain/AiqnaErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/OrderErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/ReviewErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/StoreErrorCode.java
  src/main/java/com/toyland/review/application/facade/ReviewFacade.java
  src/main/java/com/toyland/review/application/facade/ReviewFacadeImpl.java
  src/main/java/com/toyland/review/application/usecase/ReviewService.java
  src/main/java/com/toyland/review/application/usecase/ReviewServiceImpl.java
  src/main/java/com/toyland/review/presentation/ReviewController.java
  src/test/java/com/toyland/ai/QnaControllerTest.java
Labels: ✨ feat

#98 feature/#94 [User] 동적쿼리 테스트 추가
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/order/model/Order.java
  src/main/java/com/toyland/store/model/entity/Store.java
  src/main/java/com/toyland/user/model/User.java
  src/main/java/com/toyland/user/presentation/dto/UserSearchRequestDto.java
  src/test/http/user.http
  src/test/java/com/toyland/user/apllication/usecase/UserServiceTest.java
Labels: ✅ test

#103 feature/#101 http client 생성 및 테스트
  src/test/http/order.http
  src/test/http/payment.http
  src/test/http/product.http
  src/test/http/store.http
Labels: ✅ test

#92 Feature/#87 [category] 단건 조회, 수정, 삭제
  src/main/java/com/toyland/category/application/usecase/CategoryService.java
  src/main/java/com/toyland/category/application/usecase/CategoryServiceImpl.java
  src/main/java/com/toyland/category/application/usecase/dto/DeleteCategoryServiceRequestDto.java
  src/main/java/com/toyland/category/application/usecase/dto/UpdateCategoryServiceRequestDto.java
  src/main/java/com/toyland/category/model/entity/Category.java
  src/main/java/com/toyland/category/presentation/CategoryController.java
  src/main/java/com/toyland/category/presentation/UpdateCategoryRequestDto.java
  src/main/java/com/toyland/category/presentation/dto/CategoryResponseDto.java
  src/main/java/com/toyland/global/exception/type/domain/CategoryErrorCode.java
  src/test/http/category.http
  src/test/java/com/toyland/category/application/usecase/CategoryServiceTest.java
  src/test/java/com/toyland/common/IntegrationTestSupport.java
Labels: ✅ test, ✨ feat

#104 [#102] feat: Review 평점 기능 추가
  src/main/java/com/toyland/global/exception/type/domain/AiqnaErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/ReviewErrorCode.java
  src/main/java/com/toyland/global/exception/type/domain/StoreErrorCode.java
  src/main/java/com/toyland/review/application/facade/ReviewFacade.java
  src/main/java/com/toyland/review/application/facade/ReviewFacadeImpl.java
  src/main/java/com/toyland/review/application/usecase/ReviewService.java
  src/main/java/com/toyland/review/application/usecase/ReviewServiceImpl.java
  src/main/java/com/toyland/review/infrastructure/ReviewRepositoryCustom.java
  src/main/java/com/toyland/review/infrastructure/impl/ReviewRepositoryCustomImpl.java
  src/main/java/com/toyland/review/model/Review.java
  src/main/java/com/toyland/review/model/repository/ReviewRepository.java
  src/main/java/com/toyland/review/presentation/ReviewController.java
  src/main/java/com/toyland/store/model/entity/Store.java
  src/test/http/review.http
  src/test/java/com/toyland/review/ReviewServiceTest.java
Labels: ✨ feat

#107 feature/#101 swagger 설정 추가 및 구성
  build.gradle
  src/main/java/com/toyland/global/common/auditing/BaseEntity.java
  src/main/java/com/toyland/global/config/security/WebSecurityConfig.java
  src/main/java/com/toyland/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/toyland/global/config/swagger/CommonResponse.java
  src/main/java/com/toyland/global/config/swagger/Result.java
  src/main/java/com/toyland/global/config/swagger/SwaggerConfig.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/resources/application.yml
Labels: ✨ feat

#108 Feature/#93 store rud api
  src/main/java/com/toyland/category/model/repository/CategoryRepository.java
  src/main/java/com/toyland/global/exception/type/domain/StoreErrorCode.java
  src/main/java/com/toyland/product/application/facade/ProductFacade.java
  src/main/java/com/toyland/product/application/facade/ProductFacadeImpl.java
  src/main/java/com/toyland/product/application/usecase/ProductService.java
  src/main/java/com/toyland/product/application/usecase/ProductServiceImpl.java
  src/main/java/com/toyland/product/application/usecase/dto/CreateProductServiceRequestDto.java
  src/main/java/com/toyland/product/model/entity/Product.java
  src/main/java/com/toyland/product/presentation/ProductController/ProductController.java
  src/main/java/com/toyland/region/model/repository/RegionRepository.java
  src/main/java/com/toyland/store/application/usecase/StoreService.java
  src/main/java/com/toyland/store/application/usecase/StoreServiceImpl.java
  src/main/java/com/toyland/store/application/usecase/dto/DeleteStoreServiceRequestDto.java
  src/main/java/com/toyland/store/application/usecase/dto/UpdateStoreServiceRequestDto.java
  src/main/java/com/toyland/store/model/entity/Store.java
  src/main/java/com/toyland/store/model/repository/StoreRepository.java
  src/main/java/com/toyland/store/presentation/StoreController.java
  src/main/java/com/toyland/store/presentation/dto/StoreResponseDto.java
  src/main/java/com/toyland/store/presentation/dto/UpdateStoreRequestDto.java
  src/main/java/com/toyland/storecategory/model/repository/StoreCategoryRepository.java
  src/test/http/store.http
  src/test/java/com/toyland/category/application/usecase/CategoryServiceTest.java
  src/test/java/com/toyland/product/application/facade/ProductFacadeTest.java
  src/test/java/com/toyland/product/application/usecase/ProductServiceTest.java
  src/test/java/com/toyland/store/application/usecase/StoreServiceTest.java
  src/test/java/com/toyland/user/apllication/usecase/UserServiceTest.java
Labels: ✅ test, ✨ feat

#112 Feature/#99 [Order] 주문 수정 api 추가
  src/main/java/com/toyland/global/common/auditing/BaseEntity.java
  src/main/java/com/toyland/order/application/OrderService.java
  src/main/java/com/toyland/order/model/Order.java
  src/main/java/com/toyland/order/presentation/OrderController.java
Labels: ✨ feat

#124 Feature/#109 [product] serach api
  src/main/java/com/toyland/product/application/usecase/ProductService.java
  src/main/java/com/toyland/product/application/usecase/ProductServiceImpl.java
  src/main/java/com/toyland/product/infrastructure/JpaProductRepository.java
  src/main/java/com/toyland/product/infrastructure/JpaProductRepositoryCustom.java
  src/main/java/com/toyland/product/infrastructure/impl/JpaProductRepositoryCustomImpl.java
  src/main/java/com/toyland/product/model/repository/ProductRepository.java
  src/main/java/com/toyland/product/presentation/ProductController/ProductController.java
  src/main/java/com/toyland/product/presentation/dto/ProductWithStoreResponseDto.java
  src/main/java/com/toyland/product/presentation/dto/SearchProductRequestDto.java
  src/test/http/product.http
  src/test/http/store.http
  src/test/java/com/toyland/product/application/usecase/ProductServiceTest.java
Labels: ✅ test, ✨ feat

#125 refactor/#122 address, region 도메인 리팩토링 완료
  src/main/java/com/toyland/address/application/usecase/AddressServiceImpl.java
  src/main/java/com/toyland/address/infrastructure/impl/JpaAddressRepositoryCustomImpl.java
  src/main/java/com/toyland/address/model/entity/Address.java
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/global/config/swagger/response/CustomApiResponse.java
  src/main/java/com/toyland/global/exception/GlobalErrorHandler.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/test/http/address.http
  src/test/http/region.http
Labels: ♻️ refactor

#123 Feature/#121 Review Refactor
  src/main/java/com/toyland/ai/application/facade/QnaFacade.java
  src/main/java/com/toyland/ai/application/facade/QnaFacadeImpl.java
  src/main/java/com/toyland/ai/application/usecase/QnaService.java
  src/main/java/com/toyland/ai/application/usecase/QnaServiceImpl.java
  src/main/java/com/toyland/ai/infrastructure/impl/QnaRepositoryCustomImpl.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/ai/presentation/dto/QnaResponseDto.java
  src/main/java/com/toyland/review/application/facade/ReviewFacade.java
  src/main/java/com/toyland/review/application/facade/ReviewFacadeImpl.java
  src/main/java/com/toyland/review/application/usecase/ReviewService.java
  src/main/java/com/toyland/review/application/usecase/ReviewServiceImpl.java
  src/main/java/com/toyland/review/infrastructure/JpaReviewRepository.java
  src/main/java/com/toyland/review/infrastructure/ReviewRepositoryCustom.java
  src/main/java/com/toyland/review/infrastructure/impl/ReviewRepositoryCustomImpl.java
  src/main/java/com/toyland/review/model/Review.java
  src/main/java/com/toyland/review/model/repository/ReviewRepository.java
  src/main/java/com/toyland/review/presentation/ReviewController.java
  src/main/java/com/toyland/store/model/entity/Store.java
  src/test/http/aiqna.http
  src/test/http/review.http
  src/test/java/com/toyland/ai/QnaControllerTest.java
  src/test/java/com/toyland/review/ReviewServiceTest.java
Labels: ♻️ refactor

#119 Feature/#115 [Payment] 결제 단 건 조회 api, 수정/삭제 HTTP 테스트 추가
  src/main/java/com/toyland/order/model/Order.java
  src/main/java/com/toyland/payment/application/facade/PaymentFacade.java
  src/main/java/com/toyland/payment/application/facade/PaymentFacadeImpl.java
  src/main/java/com/toyland/payment/application/usecase/PaymentService.java
  src/main/java/com/toyland/payment/application/usecase/PaymentServiceImpl.java
  src/main/java/com/toyland/payment/model/entity/Payment.java
  src/main/java/com/toyland/payment/presentation/PaymentController.java
  src/main/java/com/toyland/payment/presentation/dto/request/PaymentRequestDto.java
  src/test/http/payment.http
  src/test/java/com/toyland/payment/application/usecase/PaymentServiceImplTest.java
Labels: ♻️ refactor, ✅ test, ✨ feat

#136 feature/#135 api 개수 세는 스크립트 추가
  api-statistics.sh
Labels: ✨ feat

#139 Feature/#138 [User] Swagger 추가 요구사항 적용
  docker-compose.yml
  src/main/java/com/toyland/user/application/UserService.java
  src/main/java/com/toyland/user/infrastructure/Impl/JpaUserRepositoryCustomImpl.java
  src/main/java/com/toyland/user/presentation/UserController.java
  src/main/java/com/toyland/user/presentation/dto/UpdateUserRequestDto.java
Labels: ♻️ refactor

#134 Feature/#110 category search
  src/main/java/com/toyland/category/application/usecase/CategoryService.java
  src/main/java/com/toyland/category/application/usecase/CategoryServiceImpl.java
  src/main/java/com/toyland/category/application/usecase/dto/UpdateCategoryServiceRequestDto.java
  src/main/java/com/toyland/category/infrastructure/JpaCategoryRepository.java
  src/main/java/com/toyland/category/infrastructure/JpaCategoryRepositoryCustom.java
  src/main/java/com/toyland/category/infrastructure/impl/JpaCategoryRepositoryCustomImpl.java
  src/main/java/com/toyland/category/model/repository/CategoryRepository.java
  src/main/java/com/toyland/category/model/repository/dao/SearchCategoryRequestDao.java
  src/main/java/com/toyland/category/presentation/CategoryController.java
  src/main/java/com/toyland/category/presentation/dto/CategoryResponseDto.java
  src/main/java/com/toyland/category/presentation/dto/SearchCategoryRequestDto.java
  src/main/java/com/toyland/category/presentation/dto/UpdateCategoryRequestDto.java
  src/test/http/category.http
  src/test/java/com/toyland/category/application/usecase/CategoryServiceTest.java
  src/test/java/com/toyland/product/application/facade/ProductFacadeTest.java
Labels: ✅ test, ✨ feat

#129 Feature/#120 [Order] 주문 검색 api, 동적 쿼리 작성
  src/main/java/com/toyland/global/exception/type/domain/StoreErrorCode.java
  src/main/java/com/toyland/order/application/OrderService.java
  src/main/java/com/toyland/order/infrastructure/Impl/JpaOrderRepositoryCustomImpl.java
  src/main/java/com/toyland/order/infrastructure/JpaOrderRepository.java
  src/main/java/com/toyland/order/infrastructure/JpaOrderRepositoryCustom.java
  src/main/java/com/toyland/order/model/repository/OrderRepository.java
  src/main/java/com/toyland/order/presentation/OrderController.java
  src/main/java/com/toyland/order/presentation/dto/request/OrderSearchRequestDto.java
  src/main/java/com/toyland/order/presentation/dto/response/OrderSearchResponseDto.java
  src/main/java/com/toyland/orderproduct/model/OrderProduct.java
  src/test/http/order.http
Labels: ✨ feat

#143 Feature/#128 [Payment] 결제 검색 api, 동적 쿼리 작성
  src/main/java/com/toyland/payment/application/facade/PaymentFacade.java
  src/main/java/com/toyland/payment/application/facade/PaymentFacadeImpl.java
  src/main/java/com/toyland/payment/application/usecase/PaymentService.java
  src/main/java/com/toyland/payment/application/usecase/PaymentServiceImpl.java
  src/main/java/com/toyland/payment/infrastructure/Impl/JpaPaymentRepositoryCustomImpl.java
  src/main/java/com/toyland/payment/infrastructure/JpaPaymentRepository.java
  src/main/java/com/toyland/payment/infrastructure/JpaPaymentRepositoryCustom.java
  src/main/java/com/toyland/payment/model/repository/PaymentRepository.java
  src/main/java/com/toyland/payment/presentation/PaymentController.java
  src/main/java/com/toyland/payment/presentation/dto/request/PaymentSearchRequestDto.java
  src/main/java/com/toyland/payment/presentation/dto/response/PaymentSearchResponseDto.java
  src/test/http/payment.http
Labels: ✨ feat

#144 Feature/#111 store search api 구현
  src/main/java/com/toyland/store/application/usecase/StoreService.java
  src/main/java/com/toyland/store/application/usecase/StoreServiceImpl.java
  src/main/java/com/toyland/store/infrastructure/JpaStoreRepository.java
  src/main/java/com/toyland/store/infrastructure/JpaStoreRepositoryCustom.java
  src/main/java/com/toyland/store/infrastructure/impl/JpaStoreRepositoryCustomImpl.java
  src/main/java/com/toyland/store/infrastructure/impl/dao/StoreWithOwnerResponseDao.java
  src/main/java/com/toyland/store/model/entity/Store.java
  src/main/java/com/toyland/store/model/repository/StoreRepository.java
  src/main/java/com/toyland/store/model/repository/command/SearchStoreRepositoryCommand.java
  src/main/java/com/toyland/store/presentation/StoreController.java
  src/main/java/com/toyland/store/presentation/dto/SearchStoreRequestDto.java
  src/main/java/com/toyland/store/presentation/dto/StoreWithOwnerResponseDto.java
  src/test/http/store.http
  src/test/java/com/toyland/store/application/usecase/StoreServiceTest.java
Labels: ✅ test, ✨ feat

#149 Feature/#84 store, product, category 리펙토링(swagger, read only, create uri 추가, 메서드변경 등)
  src/main/java/com/toyland/category/application/facade/CategoryFacade.java
  src/main/java/com/toyland/category/application/facade/CategoryFacadeImpl.java
  src/main/java/com/toyland/category/application/usecase/CategoryService.java
  src/main/java/com/toyland/category/application/usecase/CategoryServiceImpl.java
  src/main/java/com/toyland/category/infrastructure/impl/JpaCategoryRepositoryCustomImpl.java
  src/main/java/com/toyland/category/model/repository/dao/SearchCategoryRequestDao.java
  src/main/java/com/toyland/category/presentation/CategoryController.java
  src/main/java/com/toyland/global/config/security/annotation/HasManageCategoryRole.java
  src/main/java/com/toyland/global/config/security/annotation/HasManageProductRole.java
  src/main/java/com/toyland/global/config/security/annotation/HasManageStoreRole.java
  src/main/java/com/toyland/product/application/facade/ProductFacade.java
  src/main/java/com/toyland/product/application/facade/ProductFacadeImpl.java
  src/main/java/com/toyland/product/application/usecase/ProductService.java
  src/main/java/com/toyland/product/application/usecase/ProductServiceImpl.java
  src/main/java/com/toyland/product/infrastructure/impl/JpaProductRepositoryCustomImpl.java
  src/main/java/com/toyland/product/presentation/ProductController/ProductController.java
  src/main/java/com/toyland/store/application/facade/StoreFacade.java
  src/main/java/com/toyland/store/application/facade/StoreFacadeImpl.java
  src/main/java/com/toyland/store/application/usecase/StoreService.java
  src/main/java/com/toyland/store/application/usecase/StoreServiceImpl.java
  src/main/java/com/toyland/store/presentation/StoreController.java
  src/test/java/com/toyland/category/application/usecase/CategoryServiceTest.java
  src/test/java/com/toyland/product/application/usecase/ProductServiceTest.java
Labels: ♻️ refactor

#150 Refactor/#148 querydsl command 리팩토링
  docker-compose.yml
  src/main/java/com/toyland/region/application/facade/RegionFacade.java
  src/main/java/com/toyland/region/application/facade/RegionFacadeImpl.java
  src/main/java/com/toyland/region/application/usecase/RegionService.java
  src/main/java/com/toyland/region/application/usecase/RegionServiceImpl.java
  src/main/java/com/toyland/region/infrastructure/Impl/JpaRegionRepositoryCustomImpl.java
  src/main/java/com/toyland/region/infrastructure/JpaRegionRepositoryCustom.java
  src/main/java/com/toyland/region/model/repository/RegionRepository.java
  src/main/java/com/toyland/region/model/repository/command/SearchRegionRepositoryCommand.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/java/com/toyland/region/presentation/dto/repuest/RegionSearchRequestDto.java
  src/test/java/com/toyland/region/application/usecase/RegionServiceImplTest.java
Labels: ♻️ refactor

#152 refactor/#151 전체적 swagger 리팩토링
  .github/workflows/deploy.yml
  src/main/java/com/toyland/address/presentation/AddressController.java
  src/main/java/com/toyland/ai/presentation/QnaController.java
  src/main/java/com/toyland/category/presentation/CategoryController.java
  src/main/java/com/toyland/global/config/swagger/response/HttpSuccessCode.java
  src/main/java/com/toyland/order/presentation/OrderController.java
  src/main/java/com/toyland/payment/presentation/PaymentController.java
  src/main/java/com/toyland/product/presentation/ProductController/ProductController.java
  src/main/java/com/toyland/region/presentation/RegionController.java
  src/main/java/com/toyland/review/presentation/ReviewController.java
  src/main/java/com/toyland/review/presentation/dto/ReviewResponseDto.java
  src/main/java/com/toyland/store/presentation/StoreController.java
  src/main/java/com/toyland/user/presentation/UserController.java
  src/test/java/com/toyland/user/apllication/usecase/UserServiceTest.java
Labels: ♻️ refactor

#155 refactor/#154 User Test 수정
  src/test/java/com/toyland/user/apllication/usecase/UserServiceTest.java
Labels: ♻️ refactor

#160 refactor/#159 점검 전 수정
  src/main/java/com/toyland/global/exception/type/domain/UserErrorCode.java
  src/main/java/com/toyland/user/application/UserService.java
  src/test/http/address.http
  src/test/http/aiqna.http
  src/test/http/category.http
  src/test/http/intergration/AdminIntergrationE2ETest.http
  src/test/http/intergration/CustomerIntergrationE2ETest.http
  src/test/http/intergration/OwnerIntergrationE2ETest.http
  src/test/http/order.http
  src/test/http/payment.http
  src/test/http/product.http
  src/test/http/region.http
  src/test/http/review.http
  src/test/http/store.http
  src/test/http/user.http
  src/test/java/com/toyland/user/apllication/usecase/UserServiceTest.java
Labels: ♻️ refactor

#161 Docs/#156 README.md 작성
  README.md
Labels: 📝 docs
